@startuml
title Bewerbungsstatus

state Created : Erstellt die Bewerbung
state Unregistered : Abgemeldet
state Submitted : Bewerbung eingereicht
state DocumentMissing : Dokumente fehlen
state AdmissionCriteriaNotMet : Zulassungskriterien nicht erfüllt

[*] --> Created

Created --> DocumentMissing : Dokumente fehlen
Created --> Submitted : Bewerbung überprüft
DocumentMissing --> Submitted : Dokumente nachgereicht

state "AV" as AV {
    state Unassigned : Bewerbung nicht zugewiesen
    state Rejected : Bewerber abgelehnt
    state Accepted : Bewerber akzeptiert
    state Assigned : Bewerbung zugewiesen
}

Submitted --> Unassigned
Submitted --> DocumentMissing
Submitted --> AdmissionCriteriaNotMet
Unassigned --> Assigned
Unassigned --> Rejected
Assigned --> Rejected
Assigned --> Accepted

@enduml